app:
  dev_mode: true
mineru:
  default_backend: pipeline
  fastapi:
    url: http://localhost:8000
  vlm:
    http_client:
      server_url: http://localhost:30000
  pipeline:
    parse_method: auto
    lang: ch
    formula_enable: true
    table_enable: true
dots:
  vllm:
    url: http://localhost:8000
    model_name: dotsocr-model
    temperature: 0.1
    top_p: 1.0
    max_completion_tokens: 16384
paddleocr:
  url: http://172.20.32.127:7071/ocr
  timeout: 30000
  max_file_size: 5000
