"""文档域应用服务（按职责分子模块，对外保持原 ``document_service`` API）。"""

from app.services.documents.acl import (
    grant_permission,
    list_acl_picker_data,
    list_acl_user_candidates,
    list_document_permissions,
    list_document_shares,
    revoke_document_share,
    revoke_permission,
    set_document_shares,
)
from app.services.documents.content import (
    get_download_url,
    read_document_file_bytes,
    read_document_pdf_bytes,
)
from app.services.documents.crud import (
    complete_upload,
    create_document,
    create_initial_uploaded_version,
    delete_document_version,
    document_has_uploaded_version,
    get_document,
    is_version_uploaded,
    list_document_versions,
    move_document_to_folder,
    prepare_upload,
    publish_document_scope,
    resolve_current_version,
    save_upload_blob,
    update_document,
    update_document_status,
)
from app.services.documents.lifecycle import (
    batch_delete_documents,
    can_permanently_delete_document,
    empty_recycle_bin,
    permanently_delete_document,
    purge_document_completely,
    restore_document,
    soft_delete_document,
)
from app.services.documents.listing import (
    list_accessible_documents,
    list_all_visible_documents,
    list_compareable_documents,
    list_queryable_documents,
    list_recycle_documents,
    list_shared_documents,
    list_translatable_documents,
)

__all__ = [
    "grant_permission",
    "list_acl_picker_data",
    "list_acl_user_candidates",
    "list_document_permissions",
    "list_document_shares",
    "revoke_document_share",
    "revoke_permission",
    "set_document_shares",
    "get_download_url",
    "read_document_file_bytes",
    "read_document_pdf_bytes",
    "complete_upload",
    "create_document",
    "create_initial_uploaded_version",
    "delete_document_version",
    "document_has_uploaded_version",
    "get_document",
    "is_version_uploaded",
    "list_document_versions",
    "move_document_to_folder",
    "prepare_upload",
    "save_upload_blob",
    "publish_document_scope",
    "resolve_current_version",
    "update_document",
    "update_document_status",
    "batch_delete_documents",
    "can_permanently_delete_document",
    "empty_recycle_bin",
    "permanently_delete_document",
    "purge_document_completely",
    "restore_document",
    "soft_delete_document",
    "list_accessible_documents",
    "list_all_visible_documents",
    "list_compareable_documents",
    "list_queryable_documents",
    "list_recycle_documents",
    "list_shared_documents",
    "list_translatable_documents",
]
