import { getNaivePalette, normalizeColorScheme } from "../constants/colorSchemes.js";

/** Naive UI theme overrides — OpenAI / ChatGPT flat palettes */
export function createThemeOverrides(isDark, colorScheme = "blue", customPrimaryColor) {
  const palette = getNaivePalette(colorScheme, isDark, customPrimaryColor);
  const accentColors = {
    primaryColor: palette.primary,
    primaryColorHover: palette.primaryHover,
    primaryColorPressed: palette.primaryPressed,
    primaryColorSuppl: palette.primarySuppl,
    successColor: palette.primary,
    successColorHover: palette.primaryHover,
    successColorPressed: palette.primaryPressed,
    successColorSuppl: palette.primarySuppl,
    infoColor: palette.primary,
    infoColorHover: palette.primaryHover,
    infoColorPressed: palette.primaryPressed,
    infoColorSuppl: palette.primarySuppl,
  };

  if (isDark) {
    return {
      common: {
        ...accentColors,
        bodyColor: "transparent",
        cardColor: "#2f2f2f",
        modalColor: "#2f2f2f",
        popoverColor: "#2f2f2f",
        tableColor: "#212121",
        inputColor: "#2f2f2f",
        actionColor: "rgba(255, 255, 255, 0.08)",
        hoverColor: "rgba(255, 255, 255, 0.06)",
        borderColor: "rgba(255, 255, 255, 0.1)",
        dividerColor: "rgba(255, 255, 255, 0.08)",
        textColor1: "#ececec",
        textColor2: "#c5c5d2",
        textColor3: "#8e8ea0",
        placeholderColor: "#6e6e80",
        borderRadius: "8px",
        borderRadiusSmall: "6px",
        fontWeightStrong: "600",
        fontSize: "16px",
        fontSizeMini: "14px",
        fontSizeTiny: "14px",
        fontSizeSmall: "14px",
        fontSizeMedium: "16px",
        fontSizeLarge: "17px",
        fontSizeHuge: "19px",
        boxShadow1: "0 1px 2px rgba(0, 0, 0, 0.32)",
        boxShadow2: "0 4px 16px rgba(0, 0, 0, 0.36)",
        boxShadow3: "0 12px 40px rgba(0, 0, 0, 0.48)",
      },
      Card: {
        borderRadius: "8px",
        paddingMedium: "16px 18px",
        titleFontSizeMedium: "15px",
        titleFontWeight: "600",
        color: "#2f2f2f",
        borderColor: "rgba(255, 255, 255, 0.1)",
      },
      Button: {
        borderRadiusMedium: "8px",
        borderRadiusSmall: "6px",
        fontWeight: "500",
        heightMedium: "38px",
        heightSmall: "32px",
        fontSizeMedium: "16px",
        fontSizeSmall: "14px",
      },
      Input: {
        borderRadius: "8px",
        heightMedium: "38px",
        fontSizeMedium: "16px",
        color: "transparent",
        colorFocus: "transparent",
        border: "1px solid rgba(255, 255, 255, 0.12)",
        borderHover: "1px solid rgba(255, 255, 255, 0.18)",
        borderFocus: `1px solid ${palette.focusBorder}`,
        boxShadowFocus: palette.focusShadow,
      },
      DataTable: {
        borderRadius: "12px",
        thColor: "#2c2c2e",
        thTextColor: "#f5f5f7",
        tdColor: "#1c1c1e",
        borderColor: "rgba(255, 255, 255, 0.08)",
        fontSizeMedium: "16px",
      },
      Menu: {
        borderRadius: "8px",
        itemHeight: "42px",
        fontSize: "16px",
        itemColorActive: palette.menuActiveBg,
        itemColorActiveHover: palette.menuActiveBgHover,
        itemTextColorActive: palette.tabActive,
        itemTextColor: "#d1d1d6",
        itemTextColorHover: "#f5f5f7",
        itemIconColor: "#98989d",
        itemIconColorActive: palette.tabActive,
        itemIconColorHover: "#f5f5f7",
      },
      Tabs: {
        tabTextColorActive: palette.tabActive,
        tabTextColorHover: "#f5f5f7",
        barColor: palette.primary,
      },
      Tag: {
        borderRadius: "6px",
      },
      Popover: {
        borderRadius: "12px",
        padding: "12px",
      },
      Tooltip: {
        borderRadius: "8px",
        padding: "8px 12px",
        color: "rgba(22, 22, 32, 0.94)",
        textColor: "#f5f5f7",
        boxShadow: "0 8px 24px rgba(0, 0, 0, 0.36)",
      },
      Dropdown: {
        borderRadius: "12px",
        padding: "8px",
        color: "#2c2c2e",
        dividerColor: "rgba(255, 255, 255, 0.08)",
        optionTextColor: "#d1d1d6",
        optionTextColorHover: "#f5f5f7",
        optionTextColorActive: palette.dropdownActiveText,
        prefixColor: "#98989d",
        suffixColor: "#98989d",
        optionColorHover: "rgba(255, 255, 255, 0.06)",
        optionColorActive: palette.dropdownActiveBg,
      },
      Dialog: {
        borderRadius: "14px",
        padding: "20px 22px",
      },
    };
  }

  return {
    common: {
      ...accentColors,
      bodyColor: "transparent",
      cardColor: "#ffffff",
      modalColor: "#ffffff",
      popoverColor: "#ffffff",
      tableColor: "#ffffff",
      inputColor: "#ffffff",
      actionColor: "#f7f7f8",
      hoverColor: "rgba(0, 0, 0, 0.04)",
      borderColor: "#e5e5e5",
      dividerColor: "#ececf1",
      textColor1: "#0d0d0d",
      textColor2: "#6e6e80",
      textColor3: "#8e8ea0",
      placeholderColor: "#acacbe",
      borderRadius: "8px",
      borderRadiusSmall: "6px",
      fontWeightStrong: "600",
      fontSize: "16px",
      fontSizeMini: "14px",
      fontSizeTiny: "14px",
      fontSizeSmall: "14px",
      fontSizeMedium: "16px",
      fontSizeLarge: "17px",
      fontSizeHuge: "19px",
      boxShadow1: "0 1px 2px rgba(0, 0, 0, 0.04)",
      boxShadow2: "0 4px 16px rgba(0, 0, 0, 0.06)",
      boxShadow3: "0 8px 32px rgba(0, 0, 0, 0.1)",
    },
    Card: {
      borderRadius: "8px",
      paddingMedium: "16px 18px",
      titleFontSizeMedium: "15px",
      titleFontWeight: "600",
      color: "#ffffff",
      borderColor: "#e5e5e5",
    },
    Button: {
      borderRadiusMedium: "8px",
      borderRadiusSmall: "6px",
      fontWeight: "500",
      heightMedium: "38px",
      heightSmall: "32px",
      fontSizeMedium: "16px",
      fontSizeSmall: "14px",
    },
    Input: {
      borderRadius: "8px",
      heightMedium: "38px",
      fontSizeMedium: "16px",
      color: "transparent",
      colorFocus: "transparent",
      border: "1px solid rgba(0, 0, 0, 0.12)",
      borderHover: "1px solid rgba(0, 0, 0, 0.18)",
      borderFocus: `1px solid ${palette.focusBorder}`,
      boxShadowFocus: palette.focusShadow,
    },
    DataTable: {
      borderRadius: "12px",
      thColor: "#f5f5f7",
      thTextColor: "#1d1d1f",
      tdColor: "#ffffff",
      borderColor: "rgba(0, 0, 0, 0.06)",
      fontSizeMedium: "16px",
    },
    Menu: {
      borderRadius: "8px",
      itemHeight: "42px",
      fontSize: "16px",
      itemColorActive: palette.menuActiveBg,
      itemColorActiveHover: palette.menuActiveBgHover,
      itemTextColorActive: palette.primary,
      itemTextColor: "#6e6e80",
      itemTextColorHover: "#0d0d0d",
      itemIconColor: "#8e8ea0",
      itemIconColorActive: palette.primary,
      itemIconColorHover: "#0d0d0d",
    },
    Tabs: {
      tabTextColorActive: palette.tabActive,
      tabTextColorHover: "#0d0d0d",
      barColor: palette.primary,
    },
    Tag: {
      borderRadius: "6px",
    },
    Popover: {
      borderRadius: "12px",
      padding: "12px",
    },
    Tooltip: {
      borderRadius: "8px",
      padding: "8px 12px",
      color: "rgba(255, 255, 255, 0.96)",
      textColor: "#1d1d1f",
      boxShadow: "0 4px 16px rgba(0, 0, 0, 0.08)",
    },
    Dropdown: {
      borderRadius: "12px",
      padding: "8px",
      color: "#ffffff",
      dividerColor: "rgba(0, 0, 0, 0.06)",
      optionTextColor: "#515154",
      optionTextColorHover: "#1d1d1f",
      optionTextColorActive: palette.dropdownActiveText,
      prefixColor: "#6e6e73",
      suffixColor: "#6e6e73",
      optionColorHover: "rgba(0, 0, 0, 0.04)",
      optionColorActive: palette.dropdownActiveBg,
    },
    Dialog: {
      borderRadius: "14px",
      padding: "20px 22px",
    },
  };
}

export { normalizeColorScheme };
