import { getNaivePalette } from "../constants/colorSchemes.js";

/** Naive UI theme overrides — 统一扁平纯色风格 */
export function createThemeOverrides(isDark, colorScheme = "blue", customPrimaryColor) {
  const palette = getNaivePalette(colorScheme, isDark, customPrimaryColor);
  const accentColors = {
    primaryColor: palette.primary,
    primaryColorHover: palette.primaryHover,
    primaryColorPressed: palette.primaryPressed,
    primaryColorSuppl: palette.primarySuppl,
    successColor: palette.primary,
    successColorHover: palette.primaryHover,
    successColorPressed: palette.primaryPressed,
    successColorSuppl: palette.primarySuppl,
    infoColor: palette.primary,
    infoColorHover: palette.primaryHover,
    infoColorPressed: palette.primaryPressed,
    infoColorSuppl: palette.primarySuppl,
  };

  if (isDark) {
    return {
      common: {
        ...accentColors,
        bodyColor: "transparent",
        cardColor: "#2f2f2f",
        modalColor: "#2f2f2f",
        popoverColor: "#2f2f2f",
        tableColor: "#212121",
        inputColor: "#2f2f2f",
        actionColor: "rgba(255, 255, 255, 0.08)",
        hoverColor: "rgba(255, 255, 255, 0.06)",
        borderColor: "rgba(255, 255, 255, 0.1)",
        dividerColor: "rgba(255, 255, 255, 0.08)",
        textColor1: "#ececec",
        textColor2: "#c5c5d2",
        textColor3: "#8e8ea0",
        placeholderColor: "#6e6e80",
        borderRadius: "10px",
        borderRadiusSmall: "7px",
        fontWeightStrong: "450",
        fontSize: "13px",
        fontSizeMini: "11px",
        fontSizeTiny: "12px",
        fontSizeSmall: "12px",
        fontSizeMedium: "13px",
        fontSizeLarge: "14px",
        fontSizeHuge: "15px",
        boxShadow1: "0 1px 2px rgba(0, 0, 0, 0.32)",
        boxShadow2: "0 5px 19px rgba(0, 0, 0, 0.36)",
        boxShadow3: "0 14px 48px rgba(0, 0, 0, 0.48)",
      },
      Card: {
        borderRadius: "10px",
        paddingMedium: "14px 16px",
        titleFontSizeMedium: "13px",
        titleFontWeight: "450",
        color: "#2f2f2f",
        borderColor: "rgba(255, 255, 255, 0.1)",
      },
      Button: {
        borderRadiusMedium: "8px",   // --btn-radius
        borderRadiusSmall: "6px",    // --btn-radius-sm
        fontWeight: "500",           // --btn-font-weight
        heightMedium: "36px",        // --btn-height-md
        heightSmall: "28px",         // --btn-height-sm（列表/工具栏操作统一）
        fontSizeMedium: "13px",      // --btn-font-size
        fontSizeSmall: "12px",       // --btn-font-size-sm
      },
      Input: {
        borderRadius: "8px",
        heightMedium: "36px",
        fontSizeMedium: "13px",
        color: "transparent",
        colorFocus: "transparent",
        border: "1px solid rgba(255, 255, 255, 0.12)",
        borderHover: "1px solid rgba(255, 255, 255, 0.18)",
        borderFocus: `1px solid ${palette.focusBorder}`,
        boxShadowFocus: palette.focusShadow,
      },
      DataTable: {
        borderRadius: "0",
        thColor: "transparent",
        thTextColor: "#8e8ea0",
        tdColor: "transparent",
        borderColor: "rgba(255, 255, 255, 0.08)",
        fontSizeMedium: "13px",
      },
      Menu: {
        borderRadius: "0",
        itemHeight: "38px",
        fontSize: "13px",
        itemColorActive: palette.menuActiveBg,
        itemColorActiveHover: palette.menuActiveBgHover,
        itemTextColor: "#ececec",
        itemTextColorHover: "#ececec",
        itemTextColorActive: "#ececec",
        itemTextColorActiveHover: "#ececec",
        itemTextColorChildActive: "#ececec",
        itemTextColorChildActiveHover: "#ececec",
        itemIconColor: "#606060",
        itemIconColorHover: "#606060",
        itemIconColorActive: "#606060",
        itemIconColorActiveHover: "#606060",
        itemIconColorChildActive: "#606060",
        itemIconColorChildActiveHover: "#606060",
        arrowColor: "#606060",
        arrowColorHover: "#606060",
        arrowColorActive: "#606060",
        arrowColorActiveHover: "#606060",
        arrowColorChildActive: "#606060",
        arrowColorChildActiveHover: "#606060",
      },
      Tabs: {
        tabTextColorActive: palette.tabActive,
        tabTextColorHover: "#f5f5f7",
        barColor: "transparent",
      },
      Tag: {
        borderRadius: "6px",
      },
      Popover: {
        borderRadius: "10px",
        padding: "10px 14px",
      },
      Tooltip: {
        borderRadius: "8px",
        padding: "8px 12px",
        color: "rgba(22, 22, 32, 0.94)",
        textColor: "#f5f5f7",
        boxShadow: "0 10px 29px rgba(0, 0, 0, 0.36)",
      },
      Dropdown: {
        borderRadius: "10px",
        padding: "6px",
        color: "#2c2c2e",
        dividerColor: "rgba(255, 255, 255, 0.08)",
        optionTextColor: "#d1d1d6",
        optionTextColorHover: "#f5f5f7",
        optionTextColorActive: palette.dropdownActiveText,
        prefixColor: "#98989d",
        suffixColor: "#98989d",
        optionColorHover: "rgba(255, 255, 255, 0.06)",
        optionColorActive: palette.dropdownActiveBg,
      },
      Dialog: {
        borderRadius: "14px",
        padding: "20px 22px",
      },
      Pagination: {
        itemTextColorActive: "#c5c5d2",
        itemTextColorHover: "#ececec",
        itemBorderActive: "1px solid rgba(255,255,255,0.16)",
        itemBorderHover: "1px solid rgba(255,255,255,0.16)",
        itemColorActive: "transparent",
        itemColorActiveHover: "transparent",
        itemSizeMedium: "24px",
        itemFontSizeMedium: "11px",
        buttonIconSizeMedium: "12px",
        itemPaddingMedium: "0 3px",
        itemMarginMedium: "0 0 0 4px",
      },
    };
  }

  return {
    common: {
      ...accentColors,
      bodyColor: "transparent",
      cardColor: "#FCFCFC",
      modalColor: "#FCFCFC",
      popoverColor: "#FCFCFC",
      tableColor: "#FCFCFC",
      inputColor: "#FCFCFC",
      actionColor: "#f7f7f8",
      hoverColor: "rgba(0, 0, 0, 0.04)",
      borderColor: "rgba(0, 0, 0, 0.05)",
      dividerColor: "rgba(0, 0, 0, 0.03)",
      textColor1: "#141414",
      textColor2: "#4f4f4f",
      textColor3: "#8e8ea0",
      placeholderColor: "#acacbe",
      borderRadius: "10px",
      borderRadiusSmall: "7px",
      fontWeightStrong: "450",
      fontSize: "13px",
      fontSizeMini: "11px",
      fontSizeTiny: "12px",
      fontSizeSmall: "12px",
      fontSizeMedium: "13px",
      fontSizeLarge: "14px",
      fontSizeHuge: "15px",
      boxShadow1: "0 1px 2px rgba(0, 0, 0, 0.03)",
      boxShadow2: "0 5px 19px rgba(0, 0, 0, 0.04)",
      boxShadow3: "0 10px 38px rgba(0, 0, 0, 0.08)",
    },
    Card: {
      borderRadius: "10px",
      paddingMedium: "14px 16px",
      titleFontSizeMedium: "13px",
      titleFontWeight: "450",
      color: "#FCFCFC",
      borderColor: "rgba(0, 0, 0, 0.09)",
    },
    Button: {
      borderRadiusMedium: "8px",   // --btn-radius
      borderRadiusSmall: "6px",    // --btn-radius-sm
      fontWeight: "500",           // --btn-font-weight
      heightMedium: "36px",        // --btn-height-md
      heightSmall: "28px",         // --btn-height-sm（列表/工具栏操作统一）
      fontSizeMedium: "13px",      // --btn-font-size
      fontSizeSmall: "12px",       // --btn-font-size-sm
    },
    Input: {
      borderRadius: "8px",
      heightMedium: "36px",
      fontSizeMedium: "13px",
      color: "transparent",
      colorFocus: "transparent",
      border: "1px solid rgba(0, 0, 0, 0.12)",
      borderHover: "1px solid rgba(0, 0, 0, 0.18)",
      borderFocus: `1px solid ${palette.focusBorder}`,
      boxShadowFocus: palette.focusShadow,
    },
    DataTable: {
      borderRadius: "0",
      thColor: "transparent",
      thTextColor: "#8e8ea0",
      tdColor: "transparent",
      borderColor: "rgba(0, 0, 0, 0.06)",
      fontSizeMedium: "13px",
    },
    Menu: {
      borderRadius: "0",
      itemHeight: "38px",
      fontSize: "13px",
      itemColorActive: palette.menuActiveBg,
      itemColorActiveHover: palette.menuActiveBgHover,
      itemTextColor: "#141414",
      itemTextColorHover: "#141414",
      itemTextColorActive: "#141414",
      itemTextColorActiveHover: "#141414",
      itemTextColorChildActive: "#141414",
      itemTextColorChildActiveHover: "#141414",
      itemIconColor: "#606060",
      itemIconColorHover: "#606060",
      itemIconColorActive: "#606060",
      itemIconColorActiveHover: "#606060",
      itemIconColorChildActive: "#606060",
      itemIconColorChildActiveHover: "#606060",
      arrowColor: "#606060",
      arrowColorHover: "#606060",
      arrowColorActive: "#606060",
      arrowColorActiveHover: "#606060",
      arrowColorChildActive: "#606060",
      arrowColorChildActiveHover: "#606060",
    },
    Tabs: {
      tabTextColorActive: palette.tabActive,
      tabTextColorHover: "#141414",
      barColor: "transparent",
    },
    Tag: {
      borderRadius: "6px",
    },
    Popover: {
      borderRadius: "10px",
      padding: "10px 14px",
    },
    Tooltip: {
      borderRadius: "8px",
      padding: "8px 12px",
      color: "rgba(255, 255, 255, 0.96)",
      textColor: "#141414",
      boxShadow: "0 5px 19px rgba(0, 0, 0, 0.08)",
    },
    Dropdown: {
      borderRadius: "10px",
      padding: "6px",
      color: "#ffffff",
      dividerColor: "rgba(0, 0, 0, 0.06)",
      optionTextColor: "#141414",
      optionTextColorHover: "#141414",
      optionTextColorActive: palette.dropdownActiveText,
      prefixColor: "#606060",
      suffixColor: "#606060",
      optionColorHover: "rgba(0, 0, 0, 0.04)",
      optionColorActive: palette.dropdownActiveBg,
      optionIconColor: "#606060",
    },
    Dialog: {
      borderRadius: "14px",
      padding: "20px 22px",
    },
    Pagination: {
      itemTextColorActive: "#4f4f4f",
      itemTextColorHover: "#141414",
      itemBorderActive: "1px solid rgba(0,0,0,0.16)",
      itemBorderHover: "1px solid rgba(0,0,0,0.16)",
      itemColorActive: "transparent",
      itemColorActiveHover: "transparent",
      itemSizeMedium: "24px",
      itemFontSizeMedium: "11px",
      buttonIconSizeMedium: "12px",
      itemPaddingMedium: "0 3px",
      itemMarginMedium: "0 0 0 4px",
    },
  };
}
