import { getNaivePalette } from "../constants/colorSchemes.js";
import { DARK_THEME, LIGHT_THEME } from "../constants/themeColors.js";

/** Naive UI theme overrides — Smart Carbon Blue */
export function createThemeOverrides(isDark, colorScheme = "blue", customPrimaryColor) {
  const palette = getNaivePalette(colorScheme, isDark, customPrimaryColor);
  const accentColors = {
    primaryColor: palette.primary,
    primaryColorHover: palette.primaryHover,
    primaryColorPressed: palette.primaryPressed,
    primaryColorSuppl: palette.primarySuppl,
    successColor: "#2F9E68",
    successColorHover: "#278556",
    successColorPressed: "#1F6C46",
    successColorSuppl: "#2F9E68",
    warningColor: "#D99B2B",
    warningColorHover: "#C48920",
    warningColorPressed: "#A87418",
    warningColorSuppl: "#D99B2B",
    errorColor: "#DC5A5A",
    errorColorHover: "#C94A4A",
    errorColorPressed: "#B03E3E",
    errorColorSuppl: "#DC5A5A",
    infoColor: palette.primary,
    infoColorHover: palette.primaryHover,
    infoColorPressed: palette.primaryPressed,
    infoColorSuppl: palette.primarySuppl,
  };

  if (isDark) {
    return {
      common: {
        ...accentColors,
        successColor: "#3CB87A",
        successColorHover: "#52C98C",
        successColorPressed: "#2F9E68",
        successColorSuppl: "#3CB87A",
        warningColor: "#E0B04A",
        warningColorHover: "#EBC06A",
        warningColorPressed: "#D99B2B",
        warningColorSuppl: "#E0B04A",
        errorColor: "#E87878",
        errorColorHover: "#F09A9A",
        errorColorPressed: "#DC5A5A",
        errorColorSuppl: "#E87878",
        bodyColor: "transparent",
        cardColor: DARK_THEME.card,
        modalColor: DARK_THEME.card,
        popoverColor: DARK_THEME.card,
        tableColor: DARK_THEME.table,
        inputColor: DARK_THEME.card,
        actionColor: "rgba(255, 255, 255, 0.08)",
        hoverColor: "rgba(255, 255, 255, 0.06)",
        borderColor: DARK_THEME.border,
        dividerColor: DARK_THEME.divider,
        textColor1: DARK_THEME.text1,
        textColor2: DARK_THEME.text2,
        textColor3: DARK_THEME.text3,
        placeholderColor: "#6e6e80",
        borderRadius: "10px",
        borderRadiusSmall: "7px",
        fontWeightStrong: "450",
        fontSize: "13px",
        fontSizeMini: "11px",
        fontSizeTiny: "12px",
        fontSizeSmall: "12px",
        fontSizeMedium: "13px",
        fontSizeLarge: "14px",
        fontSizeHuge: "15px",
        boxShadow1: "0 1px 2px rgba(0, 0, 0, 0.32)",
        boxShadow2: "0 5px 19px rgba(0, 0, 0, 0.36)",
        boxShadow3: "0 14px 48px rgba(0, 0, 0, 0.48)",
      },
      Card: {
        borderRadius: "10px",
        paddingMedium: "14px 16px",
        titleFontSizeMedium: "13px",
        titleFontWeight: "450",
        color: DARK_THEME.card,
        borderColor: DARK_THEME.border,
      },
      Button: {
        borderRadiusMedium: "8px",   // --btn-radius
        borderRadiusSmall: "6px",    // --btn-radius-sm
        fontWeight: "500",           // --btn-font-weight
        heightMedium: "36px",        // --btn-height-md
        heightSmall: "28px",         // --btn-height-sm（列表/工具栏操作统一）
        fontSizeMedium: "13px",      // --btn-font-size
        fontSizeSmall: "12px",       // --btn-font-size-sm
      },
      Input: {
        borderRadius: "8px",
        heightMedium: "36px",
        fontSizeMedium: "13px",
        color: "transparent",
        colorFocus: "transparent",
        border: "1px solid rgba(255, 255, 255, 0.12)",
        borderHover: "1px solid rgba(255, 255, 255, 0.18)",
        borderFocus: `1px solid ${palette.focusBorder}`,
        boxShadowFocus: palette.focusShadow,
      },
      DataTable: {
        borderRadius: "0",
        thColor: "transparent",
        thTextColor: DARK_THEME.text3,
        tdColor: "transparent",
        borderColor: DARK_THEME.divider,
        fontSizeMedium: "13px",
      },
      Menu: {
        borderRadius: "0",
        itemHeight: "38px",
        fontSize: "13px",
        itemColorActive: palette.menuActiveBg,
        itemColorActiveHover: palette.menuActiveBgHover,
        itemTextColor: "#ACD2EB",
        itemTextColorHover: "#FFFFFF",
        itemTextColorActive: "#FFFFFF",
        itemTextColorActiveHover: "#FFFFFF",
        itemTextColorChildActive: "#FFFFFF",
        itemTextColorChildActiveHover: "#FFFFFF",
        itemIconColor: "#ACD2EB",
        itemIconColorHover: "#FFFFFF",
        itemIconColorActive: "#FFFFFF",
        itemIconColorActiveHover: "#FFFFFF",
        itemIconColorChildActive: "#FFFFFF",
        itemIconColorChildActiveHover: "#FFFFFF",
        arrowColor: "#ACD2EB",
        arrowColorHover: "#FFFFFF",
        arrowColorActive: "#FFFFFF",
        arrowColorActiveHover: "#FFFFFF",
        arrowColorChildActive: "#FFFFFF",
        arrowColorChildActiveHover: "#FFFFFF",
      },
      Tabs: {
        tabTextColorActive: palette.tabActive,
        tabTextColorHover: "#f5f5f7",
        barColor: "transparent",
      },
      Tag: {
        borderRadius: "6px",
      },
      Popover: {
        borderRadius: "10px",
        padding: "10px 14px",
      },
      Tooltip: {
        borderRadius: "8px",
        padding: "8px 12px",
        color: "rgba(13, 42, 71, 0.94)",
        textColor: "#E8EEF4",
        boxShadow: "0 10px 29px rgba(0, 0, 0, 0.36)",
      },
      Dropdown: {
        borderRadius: "10px",
        padding: "6px",
        color: "#132536",
        dividerColor: "rgba(255, 255, 255, 0.08)",
        optionTextColor: "#d1d1d6",
        optionTextColorHover: "#f5f5f7",
        optionTextColorActive: palette.dropdownActiveText,
        prefixColor: "#98989d",
        suffixColor: "#98989d",
        optionColorHover: "rgba(255, 255, 255, 0.06)",
        optionColorActive: palette.dropdownActiveBg,
      },
      Dialog: {
        borderRadius: "14px",
        padding: "20px 22px",
      },
      Pagination: {
        itemTextColorActive: DARK_THEME.text2,
        itemTextColorHover: DARK_THEME.text1,
        itemBorderActive: "1px solid rgba(255,255,255,0.16)",
        itemBorderHover: "1px solid rgba(255,255,255,0.16)",
        itemColorActive: "transparent",
        itemColorActiveHover: "transparent",
        itemSizeMedium: "24px",
        itemFontSizeMedium: "11px",
        buttonIconSizeMedium: "12px",
        itemPaddingMedium: "0 3px",
        itemMarginMedium: "0 0 0 4px",
      },
    };
  }

  return {
    common: {
      ...accentColors,
      bodyColor: "transparent",
      cardColor: LIGHT_THEME.card,
      modalColor: LIGHT_THEME.card,
      popoverColor: LIGHT_THEME.card,
      tableColor: LIGHT_THEME.card,
      inputColor: LIGHT_THEME.card,
      actionColor: "#F0F7FC",
      hoverColor: "rgba(0, 90, 158, 0.06)",
      borderColor: LIGHT_THEME.border,
      dividerColor: "rgba(217, 227, 236, 0.85)",
      textColor1: LIGHT_THEME.text1,
      textColor2: LIGHT_THEME.text2,
      textColor3: LIGHT_THEME.text3,
      placeholderColor: "#8FA0B0",
      borderRadius: "10px",
      borderRadiusSmall: "7px",
      fontWeightStrong: "450",
      fontSize: "13px",
      fontSizeMini: "11px",
      fontSizeTiny: "12px",
      fontSizeSmall: "12px",
      fontSizeMedium: "13px",
      fontSizeLarge: "14px",
      fontSizeHuge: "15px",
      boxShadow1: "0 1px 2px rgba(24, 42, 59, 0.04)",
      boxShadow2: "0 5px 19px rgba(24, 42, 59, 0.06)",
      boxShadow3: "0 10px 38px rgba(24, 42, 59, 0.1)",
    },
    Card: {
      borderRadius: "10px",
      paddingMedium: "14px 16px",
      titleFontSizeMedium: "13px",
      titleFontWeight: "450",
      color: LIGHT_THEME.card,
      borderColor: LIGHT_THEME.border,
    },
    Button: {
      borderRadiusMedium: "8px",   // --btn-radius
      borderRadiusSmall: "6px",    // --btn-radius-sm
      fontWeight: "500",           // --btn-font-weight
      heightMedium: "36px",        // --btn-height-md
      heightSmall: "28px",         // --btn-height-sm（列表/工具栏操作统一）
      fontSizeMedium: "13px",      // --btn-font-size
      fontSizeSmall: "12px",       // --btn-font-size-sm
    },
    Input: {
      borderRadius: "8px",
      heightMedium: "36px",
      fontSizeMedium: "13px",
      color: "transparent",
      colorFocus: "transparent",
      border: "1px solid #D9E3EC",
      borderHover: "1px solid #B3C5D6",
      borderFocus: `1px solid ${palette.focusBorder}`,
      boxShadowFocus: palette.focusShadow,
    },
    DataTable: {
      borderRadius: "0",
      thColor: "transparent",
      thTextColor: LIGHT_THEME.text3,
      tdColor: "transparent",
      borderColor: "rgba(217, 227, 236, 0.9)",
      fontSizeMedium: "13px",
    },
    Menu: {
      borderRadius: "0",
      itemHeight: "38px",
      fontSize: "13px",
      itemColorActive: palette.menuActiveBg,
      itemColorActiveHover: palette.menuActiveBgHover,
      itemTextColor: "#ACD2EB",
      itemTextColorHover: "#FFFFFF",
      itemTextColorActive: "#FFFFFF",
      itemTextColorActiveHover: "#FFFFFF",
      itemTextColorChildActive: "#FFFFFF",
      itemTextColorChildActiveHover: "#FFFFFF",
      itemIconColor: "#ACD2EB",
      itemIconColorHover: "#FFFFFF",
      itemIconColorActive: "#FFFFFF",
      itemIconColorActiveHover: "#FFFFFF",
      itemIconColorChildActive: "#FFFFFF",
      itemIconColorChildActiveHover: "#FFFFFF",
      arrowColor: "#ACD2EB",
      arrowColorHover: "#FFFFFF",
      arrowColorActive: "#FFFFFF",
      arrowColorActiveHover: "#FFFFFF",
      arrowColorChildActive: "#FFFFFF",
      arrowColorChildActiveHover: "#FFFFFF",
    },
    Tabs: {
      tabTextColorActive: palette.tabActive,
      tabTextColorHover: LIGHT_THEME.text1,
      barColor: "transparent",
    },
    Tag: {
      borderRadius: "6px",
    },
    Popover: {
      borderRadius: "10px",
      padding: "10px 14px",
    },
    Tooltip: {
      borderRadius: "8px",
      padding: "8px 12px",
      color: "rgba(255, 255, 255, 0.96)",
      textColor: LIGHT_THEME.text1,
      boxShadow: "0 5px 19px rgba(24, 42, 59, 0.1)",
    },
    Dropdown: {
      borderRadius: "10px",
      padding: "6px",
      color: "#ffffff",
      dividerColor: LIGHT_THEME.border,
      optionTextColor: LIGHT_THEME.text1,
      optionTextColorHover: LIGHT_THEME.text1,
      optionTextColorActive: palette.dropdownActiveText,
      prefixColor: LIGHT_THEME.text3,
      suffixColor: LIGHT_THEME.text3,
      optionColorHover: "rgba(0, 90, 158, 0.06)",
      optionColorActive: palette.dropdownActiveBg,
      optionIconColor: LIGHT_THEME.text3,
    },
    Dialog: {
      borderRadius: "14px",
      padding: "20px 22px",
    },
    Pagination: {
      itemTextColorActive: LIGHT_THEME.text2,
      itemTextColorHover: LIGHT_THEME.text1,
      itemBorderActive: "1px solid #D9E3EC",
      itemBorderHover: "1px solid #D9E3EC",
      itemColorActive: "transparent",
      itemColorActiveHover: "transparent",
      itemSizeMedium: "24px",
      itemFontSizeMedium: "11px",
      buttonIconSizeMedium: "12px",
      itemPaddingMedium: "0 3px",
      itemMarginMedium: "0 0 0 4px",
    },
  };
}
