"""默认本体种子数据 — 从 ontology_service.py 提取。

Neo4j 初始化时使用的默认实体类型和关系类型定义。
"""

from __future__ import annotations

from typing import Any

DEFAULT_ENTITY_TYPES: list[dict[str, Any]] = [
    {
        "code": "org",
        "label": "组织",
        "color": "blue",
        "icon": "business",
        "sort_order": 10,
        "property_schema": {
            "full_name": {"type": "string", "required": False, "description": "组织全称"},
        },
    },
    {
        "code": "person",
        "label": "人员",
        "color": "green",
        "icon": "person",
        "sort_order": 20,
        "property_schema": {
            "email": {"type": "string", "required": False, "description": "邮箱"},
            "phone": {"type": "string", "required": False, "description": "电话"},
        },
    },
    {
        "code": "doc",
        "label": "文档",
        "color": "purple",
        "icon": "document-text",
        "sort_order": 30,
        "property_schema": {
            "document_id": {"type": "string", "required": False, "description": "平台文档 ID"},
        },
    },
    {
        "code": "regulation",
        "label": "法规/标准",
        "color": "orange",
        "icon": "scale",
        "sort_order": 40,
        "property_schema": {
            "effective_date": {"type": "date", "required": False, "description": "生效日期"},
            "issuing_body": {"type": "string", "required": False, "description": "发布机构"},
        },
    },
    {
        "code": "project",
        "label": "项目",
        "color": "pink",
        "icon": "folder-open",
        "sort_order": 50,
        "property_schema": {
            "status": {"type": "string", "required": False, "description": "项目状态"},
            "start_date": {"type": "date", "required": False, "description": "开始日期"},
        },
    },
    {
        "code": "metric",
        "label": "指标",
        "color": "yellow",
        "icon": "analytics",
        "sort_order": 60,
        "property_schema": {
            "unit": {"type": "string", "required": False, "description": "单位"},
            "frequency": {"type": "string", "required": False, "description": "更新频率"},
        },
    },
    {
        "code": "tool",
        "label": "工具",
        "color": "teal",
        "icon": "build",
        "sort_order": 25,
        "property_schema": {},
    },
    {
        "code": "skill",
        "label": "技能",
        "color": "indigo",
        "icon": "code",
        "sort_order": 35,
        "property_schema": {},
    },
    {
        "code": "agent",
        "label": "智能体",
        "color": "cyan",
        "icon": "robot",
        "sort_order": 15,
        "property_schema": {},
    },
    {
        "code": "memory",
        "label": "记忆",
        "color": "teal",
        "icon": "bookmark",
        "sort_order": 45,
        "property_schema": {},
    },
]

DEFAULT_RELATION_TYPES: list[dict[str, Any]] = [
    {
        "code": "contains",
        "label": "包含",
        "domain_types": [],
        "range_types": [],
        "transitive": True,
        "inverse_of": "part_of",
        "symmetric": False,
        "sort_order": 10,
    },
    {
        "code": "part_of",
        "label": "属于",
        "domain_types": [],
        "range_types": [],
        "transitive": True,
        "inverse_of": "contains",
        "symmetric": False,
        "sort_order": 12,
    },
    {
        "code": "employs",
        "label": "任职",
        "domain_types": ["org"],
        "range_types": ["person"],
        "transitive": False,
        "inverse_of": "member_of",
        "symmetric": False,
        "sort_order": 20,
    },
    {
        "code": "member_of",
        "label": "成员",
        "domain_types": ["person"],
        "range_types": ["org"],
        "transitive": False,
        "inverse_of": "employs",
        "symmetric": False,
        "sort_order": 22,
    },
    {
        "code": "references",
        "label": "引用",
        "domain_types": [],
        "range_types": [],
        "transitive": False,
        "inverse_of": "referenced_by",
        "symmetric": False,
        "sort_order": 30,
    },
    {
        "code": "referenced_by",
        "label": "被引用",
        "domain_types": [],
        "range_types": [],
        "transitive": False,
        "inverse_of": "references",
        "symmetric": False,
        "sort_order": 32,
    },
    {
        "code": "based_on",
        "label": "依据",
        "domain_types": [],
        "range_types": [],
        "transitive": False,
        "inverse_of": "basis_for",
        "symmetric": False,
        "sort_order": 40,
    },
    {
        "code": "constrains",
        "label": "约束",
        "domain_types": ["regulation", "policy"],
        "range_types": ["metric", "project"],
        "transitive": True,
        "inverse_of": "constrained_by",
        "symmetric": False,
        "sort_order": 60,
    },
    {
        "code": "constrained_by",
        "label": "受约束于",
        "domain_types": ["metric", "project"],
        "range_types": ["regulation", "policy"],
        "transitive": True,
        "inverse_of": "constrains",
        "symmetric": False,
        "sort_order": 62,
    },
    {
        "code": "produces",
        "label": "产出",
        "domain_types": ["project"],
        "range_types": ["metric", "doc"],
        "transitive": False,
        "inverse_of": "produced_by",
        "symmetric": False,
        "sort_order": 70,
    },
    {
        "code": "responsible",
        "label": "负责",
        "domain_types": ["person"],
        "range_types": ["project"],
        "transitive": False,
        "inverse_of": "overseen_by",
        "symmetric": False,
        "sort_order": 50,
    },
    {
        "code": "overseen_by",
        "label": "受监管",
        "domain_types": ["project"],
        "range_types": ["person"],
        "transitive": False,
        "inverse_of": "responsible",
        "symmetric": False,
        "sort_order": 52,
    },
    {
        "code": "has_tool",
        "label": "拥有工具",
        "domain_types": ["agent"],
        "range_types": ["tool"],
        "transitive": False,
        "inverse_of": "",
        "symmetric": False,
        "sort_order": 25,
    },
    {
        "code": "has_skill",
        "label": "绑定技能",
        "domain_types": ["agent"],
        "range_types": ["skill"],
        "transitive": False,
        "inverse_of": "",
        "symmetric": False,
        "sort_order": 28,
    },
    {
        "code": "orchestrates",
        "label": "编排工具",
        "domain_types": ["skill"],
        "range_types": ["tool"],
        "transitive": False,
        "inverse_of": "",
        "symmetric": False,
        "sort_order": 29,
    },
    {
        "code": "produced_by",
        "label": "产自",
        "domain_types": ["metric", "doc"],
        "range_types": ["project"],
        "transitive": False,
        "inverse_of": "produces",
        "symmetric": False,
        "sort_order": 72,
    },
    {
        "code": "basis_for",
        "label": "被依据",
        "domain_types": [],
        "range_types": [],
        "transitive": False,
        "inverse_of": "based_on",
        "symmetric": False,
        "sort_order": 42,
    },
]
